#SSD
set_property IOSTANDARD LVCMOS33 [get_ports {ctrl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctrl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctrl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ctrl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]
set_property PACKAGE_PIN W7 [get_ports {segs[7]}]
set_property PACKAGE_PIN W6 [get_ports {segs[6]}]
set_property PACKAGE_PIN U8 [get_ports {segs[5]}]
set_property PACKAGE_PIN V8 [get_ports {segs[4]}]
set_property PACKAGE_PIN U5 [get_ports {segs[3]}]
set_property PACKAGE_PIN V5 [get_ports {segs[2]}]
set_property PACKAGE_PIN U7 [get_ports {segs[1]}]
set_property PACKAGE_PIN V7 [get_ports {segs[0]}]
set_property PACKAGE_PIN W4 [get_ports {ctrl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ctrl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ctrl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ctrl[0]}]

# Clock
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

# Active high reset
set_property PACKAGE_PIN V17 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

#Keyboard
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]

#Buttons
#set_property PACKAGE_PIN U18 [get_ports btnC]
#set_property IOSTANDARD LVCMOS33 [get_ports btnC]
#set_property PACKAGE_PIN T18 [get_ports btnU]
#set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN W19 [get_ports pbL]
set_property IOSTANDARD LVCMOS33 [get_ports pbL]
set_property PACKAGE_PIN T17 [get_ports pbR]
set_property IOSTANDARD LVCMOS33 [get_ports pbR]

#LEDs
set_property PACKAGE_PIN L1 [get_ports floor1_led]
set_property PACKAGE_PIN P1 [get_ports floor2_led]
set_property PACKAGE_PIN N3 [get_ports floor3_led]
set_property PACKAGE_PIN P3 [get_ports floor4_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor1_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor2_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor3_led]
set_property IOSTANDARD LVCMOS33 [get_ports floor4_led]

set_property IOSTANDARD LVCMOS33 [get_ports door_close_led]
set_property IOSTANDARD LVCMOS33 [get_ports door_open_led]
set_property PACKAGE_PIN U16 [get_ports door_close_led]
set_property PACKAGE_PIN E19 [get_ports door_open_led]

set_property IOSTANDARD LVCMOS33 [get_ports out1_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out2_down_led]
set_property IOSTANDARD LVCMOS33 [get_ports out2_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out3_down_led]
set_property IOSTANDARD LVCMOS33 [get_ports out3_up_led]
set_property IOSTANDARD LVCMOS33 [get_ports out4_down_led]
set_property PACKAGE_PIN W3 [get_ports out1_up_led]
set_property PACKAGE_PIN V3 [get_ports out2_up_led]
set_property PACKAGE_PIN V13 [get_ports out2_down_led]
set_property PACKAGE_PIN V14 [get_ports out3_up_led]
set_property PACKAGE_PIN U14 [get_ports out3_down_led]
set_property PACKAGE_PIN U15 [get_ports out4_down_led]

# Pmod I2S 
set_property PACKAGE_PIN A14 [get_ports {audio_mclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_mclk}]
set_property PACKAGE_PIN A16 [get_ports {audio_lrck}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_lrck}]
set_property PACKAGE_PIN B15 [get_ports {audio_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sck}]
set_property PACKAGE_PIN B16 [get_ports {audio_sdin}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_sdin}]

#VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]